x = int(input('Check if number is even or odd: ')) 
def EvenOdd(x): 
	match x:
		 case 0: 
 			 return 'Even'
		 case 1: 
 			 return 'Odd'
		 case 2: 
 			 return 'Even'
		 case 3: 
 			 return 'Odd'
		 case 4: 
 			 return 'Even'
		 case 5: 
 			 return 'Odd'
		 case 6: 
 			 return 'Even'
		 case 7: 
 			 return 'Odd'
		 case 8: 
 			 return 'Even'
		 case 9: 
 			 return 'Odd'
		 case 10: 
 			 return 'Even'
		 case 11: 
 			 return 'Odd'
		 case 12: 
 			 return 'Even'
		 case 13: 
 			 return 'Odd'
		 case 14: 
 			 return 'Even'
		 case 15: 
 			 return 'Odd'
		 case 16: 
 			 return 'Even'
		 case 17: 
 			 return 'Odd'
		 case 18: 
 			 return 'Even'
		 case 19: 
 			 return 'Odd'
		 case 20: 
 			 return 'Even'
		 case 21: 
 			 return 'Odd'
		 case 22: 
 			 return 'Even'
		 case 23: 
 			 return 'Odd'
		 case 24: 
 			 return 'Even'
		 case 25: 
 			 return 'Odd'
		 case 26: 
 			 return 'Even'
		 case 27: 
 			 return 'Odd'
		 case 28: 
 			 return 'Even'
		 case 29: 
 			 return 'Odd'
		 case 30: 
 			 return 'Even'
		 case 31: 
 			 return 'Odd'
		 case 32: 
 			 return 'Even'
		 case 33: 
 			 return 'Odd'
		 case 34: 
 			 return 'Even'
		 case 35: 
 			 return 'Odd'
		 case 36: 
 			 return 'Even'
		 case 37: 
 			 return 'Odd'
		 case 38: 
 			 return 'Even'
		 case 39: 
 			 return 'Odd'
		 case 40: 
 			 return 'Even'
		 case 41: 
 			 return 'Odd'
		 case 42: 
 			 return 'Even'
		 case 43: 
 			 return 'Odd'
		 case 44: 
 			 return 'Even'
		 case 45: 
 			 return 'Odd'
		 case 46: 
 			 return 'Even'
		 case 47: 
 			 return 'Odd'
		 case 48: 
 			 return 'Even'
		 case 49: 
 			 return 'Odd'
		 case 50: 
 			 return 'Even'
		 case 51: 
 			 return 'Odd'
		 case 52: 
 			 return 'Even'
		 case 53: 
 			 return 'Odd'
		 case 54: 
 			 return 'Even'
		 case 55: 
 			 return 'Odd'
		 case 56: 
 			 return 'Even'
		 case 57: 
 			 return 'Odd'
		 case 58: 
 			 return 'Even'
		 case 59: 
 			 return 'Odd'
		 case 60: 
 			 return 'Even'
		 case 61: 
 			 return 'Odd'
		 case 62: 
 			 return 'Even'
		 case 63: 
 			 return 'Odd'
		 case 64: 
 			 return 'Even'
		 case 65: 
 			 return 'Odd'
		 case 66: 
 			 return 'Even'
		 case 67: 
 			 return 'Odd'
		 case 68: 
 			 return 'Even'
		 case 69: 
 			 return 'Odd'
		 case 70: 
 			 return 'Even'
		 case 71: 
 			 return 'Odd'
		 case 72: 
 			 return 'Even'
		 case 73: 
 			 return 'Odd'
		 case 74: 
 			 return 'Even'
		 case 75: 
 			 return 'Odd'
		 case 76: 
 			 return 'Even'
		 case 77: 
 			 return 'Odd'
		 case 78: 
 			 return 'Even'
		 case 79: 
 			 return 'Odd'
		 case 80: 
 			 return 'Even'
		 case 81: 
 			 return 'Odd'
		 case 82: 
 			 return 'Even'
		 case 83: 
 			 return 'Odd'
		 case 84: 
 			 return 'Even'
		 case 85: 
 			 return 'Odd'
		 case 86: 
 			 return 'Even'
		 case 87: 
 			 return 'Odd'
		 case 88: 
 			 return 'Even'
		 case 89: 
 			 return 'Odd'
		 case 90: 
 			 return 'Even'
		 case 91: 
 			 return 'Odd'
		 case 92: 
 			 return 'Even'
		 case 93: 
 			 return 'Odd'
		 case 94: 
 			 return 'Even'
		 case 95: 
 			 return 'Odd'
		 case 96: 
 			 return 'Even'
		 case 97: 
 			 return 'Odd'
		 case 98: 
 			 return 'Even'
		 case 99: 
 			 return 'Odd'
		 case 100: 
 			 return 'Even'
		 case 101: 
 			 return 'Odd'
		 case 102: 
 			 return 'Even'
		 case 103: 
 			 return 'Odd'
		 case 104: 
 			 return 'Even'
		 case 105: 
 			 return 'Odd'
		 case 106: 
 			 return 'Even'
		 case 107: 
 			 return 'Odd'
		 case 108: 
 			 return 'Even'
		 case 109: 
 			 return 'Odd'
		 case 110: 
 			 return 'Even'
		 case 111: 
 			 return 'Odd'
		 case 112: 
 			 return 'Even'
		 case 113: 
 			 return 'Odd'
		 case 114: 
 			 return 'Even'
		 case 115: 
 			 return 'Odd'
		 case 116: 
 			 return 'Even'
		 case 117: 
 			 return 'Odd'
		 case 118: 
 			 return 'Even'
		 case 119: 
 			 return 'Odd'
		 case 120: 
 			 return 'Even'
		 case 121: 
 			 return 'Odd'
		 case 122: 
 			 return 'Even'
		 case 123: 
 			 return 'Odd'
		 case 124: 
 			 return 'Even'
		 case 125: 
 			 return 'Odd'
		 case 126: 
 			 return 'Even'
		 case 127: 
 			 return 'Odd'
		 case 128: 
 			 return 'Even'
		 case 129: 
 			 return 'Odd'
		 case 130: 
 			 return 'Even'
		 case 131: 
 			 return 'Odd'
		 case 132: 
 			 return 'Even'
		 case 133: 
 			 return 'Odd'
		 case 134: 
 			 return 'Even'
		 case 135: 
 			 return 'Odd'
		 case 136: 
 			 return 'Even'
		 case 137: 
 			 return 'Odd'
		 case 138: 
 			 return 'Even'
		 case 139: 
 			 return 'Odd'
		 case 140: 
 			 return 'Even'
		 case 141: 
 			 return 'Odd'
		 case 142: 
 			 return 'Even'
		 case 143: 
 			 return 'Odd'
		 case 144: 
 			 return 'Even'
		 case 145: 
 			 return 'Odd'
		 case 146: 
 			 return 'Even'
		 case 147: 
 			 return 'Odd'
		 case 148: 
 			 return 'Even'
		 case 149: 
 			 return 'Odd'
		 case 150: 
 			 return 'Even'
		 case 151: 
 			 return 'Odd'
		 case 152: 
 			 return 'Even'
		 case 153: 
 			 return 'Odd'
		 case 154: 
 			 return 'Even'
		 case 155: 
 			 return 'Odd'
		 case 156: 
 			 return 'Even'
		 case 157: 
 			 return 'Odd'
		 case 158: 
 			 return 'Even'
		 case 159: 
 			 return 'Odd'
		 case 160: 
 			 return 'Even'
		 case 161: 
 			 return 'Odd'
		 case 162: 
 			 return 'Even'
		 case 163: 
 			 return 'Odd'
		 case 164: 
 			 return 'Even'
		 case 165: 
 			 return 'Odd'
		 case 166: 
 			 return 'Even'
		 case 167: 
 			 return 'Odd'
		 case 168: 
 			 return 'Even'
		 case 169: 
 			 return 'Odd'
		 case 170: 
 			 return 'Even'
		 case 171: 
 			 return 'Odd'
		 case 172: 
 			 return 'Even'
		 case 173: 
 			 return 'Odd'
		 case 174: 
 			 return 'Even'
		 case 175: 
 			 return 'Odd'
		 case 176: 
 			 return 'Even'
		 case 177: 
 			 return 'Odd'
		 case 178: 
 			 return 'Even'
		 case 179: 
 			 return 'Odd'
		 case 180: 
 			 return 'Even'
		 case 181: 
 			 return 'Odd'
		 case 182: 
 			 return 'Even'
		 case 183: 
 			 return 'Odd'
		 case 184: 
 			 return 'Even'
		 case 185: 
 			 return 'Odd'
		 case 186: 
 			 return 'Even'
		 case 187: 
 			 return 'Odd'
		 case 188: 
 			 return 'Even'
		 case 189: 
 			 return 'Odd'
		 case 190: 
 			 return 'Even'
		 case 191: 
 			 return 'Odd'
		 case 192: 
 			 return 'Even'
		 case 193: 
 			 return 'Odd'
		 case 194: 
 			 return 'Even'
		 case 195: 
 			 return 'Odd'
		 case 196: 
 			 return 'Even'
		 case 197: 
 			 return 'Odd'
		 case 198: 
 			 return 'Even'
		 case 199: 
 			 return 'Odd'
		 case 200: 
 			 return 'Even'
		 case 201: 
 			 return 'Odd'
		 case 202: 
 			 return 'Even'
		 case 203: 
 			 return 'Odd'
		 case 204: 
 			 return 'Even'
		 case 205: 
 			 return 'Odd'
		 case 206: 
 			 return 'Even'
		 case 207: 
 			 return 'Odd'
		 case 208: 
 			 return 'Even'
		 case 209: 
 			 return 'Odd'
		 case 210: 
 			 return 'Even'
		 case 211: 
 			 return 'Odd'
		 case 212: 
 			 return 'Even'
		 case 213: 
 			 return 'Odd'
		 case 214: 
 			 return 'Even'
		 case 215: 
 			 return 'Odd'
		 case 216: 
 			 return 'Even'
		 case 217: 
 			 return 'Odd'
		 case 218: 
 			 return 'Even'
		 case 219: 
 			 return 'Odd'
		 case 220: 
 			 return 'Even'
		 case 221: 
 			 return 'Odd'
		 case 222: 
 			 return 'Even'
		 case 223: 
 			 return 'Odd'
		 case 224: 
 			 return 'Even'
		 case 225: 
 			 return 'Odd'
		 case 226: 
 			 return 'Even'
		 case 227: 
 			 return 'Odd'
		 case 228: 
 			 return 'Even'
		 case 229: 
 			 return 'Odd'
		 case 230: 
 			 return 'Even'
		 case 231: 
 			 return 'Odd'
		 case 232: 
 			 return 'Even'
		 case 233: 
 			 return 'Odd'
		 case 234: 
 			 return 'Even'
		 case 235: 
 			 return 'Odd'
		 case 236: 
 			 return 'Even'
		 case 237: 
 			 return 'Odd'
		 case 238: 
 			 return 'Even'
		 case 239: 
 			 return 'Odd'
		 case 240: 
 			 return 'Even'
		 case 241: 
 			 return 'Odd'
		 case 242: 
 			 return 'Even'
		 case 243: 
 			 return 'Odd'
		 case 244: 
 			 return 'Even'
		 case 245: 
 			 return 'Odd'
		 case 246: 
 			 return 'Even'
		 case 247: 
 			 return 'Odd'
		 case 248: 
 			 return 'Even'
		 case 249: 
 			 return 'Odd'
		 case 250: 
 			 return 'Even'
		 case 251: 
 			 return 'Odd'
		 case 252: 
 			 return 'Even'
		 case 253: 
 			 return 'Odd'
		 case 254: 
 			 return 'Even'
		 case 255: 
 			 return 'Odd'
		 case 256: 
 			 return 'Even'
		 case 257: 
 			 return 'Odd'
		 case 258: 
 			 return 'Even'
		 case 259: 
 			 return 'Odd'
		 case 260: 
 			 return 'Even'
		 case 261: 
 			 return 'Odd'
		 case 262: 
 			 return 'Even'
		 case 263: 
 			 return 'Odd'
		 case 264: 
 			 return 'Even'
		 case 265: 
 			 return 'Odd'
		 case 266: 
 			 return 'Even'
		 case 267: 
 			 return 'Odd'
		 case 268: 
 			 return 'Even'
		 case 269: 
 			 return 'Odd'
		 case 270: 
 			 return 'Even'
		 case 271: 
 			 return 'Odd'
		 case 272: 
 			 return 'Even'
		 case 273: 
 			 return 'Odd'
		 case 274: 
 			 return 'Even'
		 case 275: 
 			 return 'Odd'
		 case 276: 
 			 return 'Even'
		 case 277: 
 			 return 'Odd'
		 case 278: 
 			 return 'Even'
		 case 279: 
 			 return 'Odd'
		 case 280: 
 			 return 'Even'
		 case 281: 
 			 return 'Odd'
		 case 282: 
 			 return 'Even'
		 case 283: 
 			 return 'Odd'
		 case 284: 
 			 return 'Even'
		 case 285: 
 			 return 'Odd'
		 case 286: 
 			 return 'Even'
		 case 287: 
 			 return 'Odd'
		 case 288: 
 			 return 'Even'
		 case 289: 
 			 return 'Odd'
		 case 290: 
 			 return 'Even'
		 case 291: 
 			 return 'Odd'
		 case 292: 
 			 return 'Even'
		 case 293: 
 			 return 'Odd'
		 case 294: 
 			 return 'Even'
		 case 295: 
 			 return 'Odd'
		 case 296: 
 			 return 'Even'
		 case 297: 
 			 return 'Odd'
		 case 298: 
 			 return 'Even'
		 case 299: 
 			 return 'Odd'
		 case 300: 
 			 return 'Even'
		 case 301: 
 			 return 'Odd'
		 case 302: 
 			 return 'Even'
		 case 303: 
 			 return 'Odd'
		 case 304: 
 			 return 'Even'
		 case 305: 
 			 return 'Odd'
		 case 306: 
 			 return 'Even'
		 case 307: 
 			 return 'Odd'
		 case 308: 
 			 return 'Even'
		 case 309: 
 			 return 'Odd'
		 case 310: 
 			 return 'Even'
		 case 311: 
 			 return 'Odd'
		 case 312: 
 			 return 'Even'
		 case 313: 
 			 return 'Odd'
		 case 314: 
 			 return 'Even'
		 case 315: 
 			 return 'Odd'
		 case 316: 
 			 return 'Even'
		 case 317: 
 			 return 'Odd'
		 case 318: 
 			 return 'Even'
		 case 319: 
 			 return 'Odd'
		 case 320: 
 			 return 'Even'
		 case 321: 
 			 return 'Odd'
		 case 322: 
 			 return 'Even'
		 case 323: 
 			 return 'Odd'
		 case 324: 
 			 return 'Even'
		 case 325: 
 			 return 'Odd'
		 case 326: 
 			 return 'Even'
		 case 327: 
 			 return 'Odd'
		 case 328: 
 			 return 'Even'
		 case 329: 
 			 return 'Odd'
		 case 330: 
 			 return 'Even'
		 case 331: 
 			 return 'Odd'
		 case 332: 
 			 return 'Even'
		 case 333: 
 			 return 'Odd'
		 case 334: 
 			 return 'Even'
		 case 335: 
 			 return 'Odd'
		 case 336: 
 			 return 'Even'
		 case 337: 
 			 return 'Odd'
		 case 338: 
 			 return 'Even'
		 case 339: 
 			 return 'Odd'
		 case 340: 
 			 return 'Even'
		 case 341: 
 			 return 'Odd'
		 case 342: 
 			 return 'Even'
		 case 343: 
 			 return 'Odd'
		 case 344: 
 			 return 'Even'
		 case 345: 
 			 return 'Odd'
		 case 346: 
 			 return 'Even'
		 case 347: 
 			 return 'Odd'
		 case 348: 
 			 return 'Even'
		 case 349: 
 			 return 'Odd'
		 case 350: 
 			 return 'Even'
		 case 351: 
 			 return 'Odd'
		 case 352: 
 			 return 'Even'
		 case 353: 
 			 return 'Odd'
		 case 354: 
 			 return 'Even'
		 case 355: 
 			 return 'Odd'
		 case 356: 
 			 return 'Even'
		 case 357: 
 			 return 'Odd'
		 case 358: 
 			 return 'Even'
		 case 359: 
 			 return 'Odd'
		 case 360: 
 			 return 'Even'
		 case 361: 
 			 return 'Odd'
		 case 362: 
 			 return 'Even'
		 case 363: 
 			 return 'Odd'
		 case 364: 
 			 return 'Even'
		 case 365: 
 			 return 'Odd'
		 case 366: 
 			 return 'Even'
		 case 367: 
 			 return 'Odd'
		 case 368: 
 			 return 'Even'
		 case 369: 
 			 return 'Odd'
		 case 370: 
 			 return 'Even'
		 case 371: 
 			 return 'Odd'
		 case 372: 
 			 return 'Even'
		 case 373: 
 			 return 'Odd'
		 case 374: 
 			 return 'Even'
		 case 375: 
 			 return 'Odd'
		 case 376: 
 			 return 'Even'
		 case 377: 
 			 return 'Odd'
		 case 378: 
 			 return 'Even'
		 case 379: 
 			 return 'Odd'
		 case 380: 
 			 return 'Even'
		 case 381: 
 			 return 'Odd'
		 case 382: 
 			 return 'Even'
		 case 383: 
 			 return 'Odd'
		 case 384: 
 			 return 'Even'
		 case 385: 
 			 return 'Odd'
		 case 386: 
 			 return 'Even'
		 case 387: 
 			 return 'Odd'
		 case 388: 
 			 return 'Even'
		 case 389: 
 			 return 'Odd'
		 case 390: 
 			 return 'Even'
		 case 391: 
 			 return 'Odd'
		 case 392: 
 			 return 'Even'
		 case 393: 
 			 return 'Odd'
		 case 394: 
 			 return 'Even'
		 case 395: 
 			 return 'Odd'
		 case 396: 
 			 return 'Even'
		 case 397: 
 			 return 'Odd'
		 case 398: 
 			 return 'Even'
		 case 399: 
 			 return 'Odd'
		 case 400: 
 			 return 'Even'
		 case 401: 
 			 return 'Odd'
		 case 402: 
 			 return 'Even'
		 case 403: 
 			 return 'Odd'
		 case 404: 
 			 return 'Even'
		 case 405: 
 			 return 'Odd'
		 case 406: 
 			 return 'Even'
		 case 407: 
 			 return 'Odd'
		 case 408: 
 			 return 'Even'
		 case 409: 
 			 return 'Odd'
		 case 410: 
 			 return 'Even'
		 case 411: 
 			 return 'Odd'
		 case 412: 
 			 return 'Even'
		 case 413: 
 			 return 'Odd'
		 case 414: 
 			 return 'Even'
		 case 415: 
 			 return 'Odd'
		 case 416: 
 			 return 'Even'
		 case 417: 
 			 return 'Odd'
		 case 418: 
 			 return 'Even'
		 case 419: 
 			 return 'Odd'
		 case 420: 
 			 return 'Even'
		 case 421: 
 			 return 'Odd'
		 case 422: 
 			 return 'Even'
		 case 423: 
 			 return 'Odd'
		 case 424: 
 			 return 'Even'
		 case 425: 
 			 return 'Odd'
		 case 426: 
 			 return 'Even'
		 case 427: 
 			 return 'Odd'
		 case 428: 
 			 return 'Even'
		 case 429: 
 			 return 'Odd'
		 case 430: 
 			 return 'Even'
		 case 431: 
 			 return 'Odd'
		 case 432: 
 			 return 'Even'
		 case 433: 
 			 return 'Odd'
		 case 434: 
 			 return 'Even'
		 case 435: 
 			 return 'Odd'
		 case 436: 
 			 return 'Even'
		 case 437: 
 			 return 'Odd'
		 case 438: 
 			 return 'Even'
		 case 439: 
 			 return 'Odd'
		 case 440: 
 			 return 'Even'
		 case 441: 
 			 return 'Odd'
		 case 442: 
 			 return 'Even'
		 case 443: 
 			 return 'Odd'
		 case 444: 
 			 return 'Even'
		 case 445: 
 			 return 'Odd'
		 case 446: 
 			 return 'Even'
		 case 447: 
 			 return 'Odd'
		 case 448: 
 			 return 'Even'
		 case 449: 
 			 return 'Odd'
		 case 450: 
 			 return 'Even'
		 case 451: 
 			 return 'Odd'
		 case 452: 
 			 return 'Even'
		 case 453: 
 			 return 'Odd'
		 case 454: 
 			 return 'Even'
		 case 455: 
 			 return 'Odd'
		 case 456: 
 			 return 'Even'
		 case 457: 
 			 return 'Odd'
		 case 458: 
 			 return 'Even'
		 case 459: 
 			 return 'Odd'
		 case 460: 
 			 return 'Even'
		 case 461: 
 			 return 'Odd'
		 case 462: 
 			 return 'Even'
		 case 463: 
 			 return 'Odd'
		 case 464: 
 			 return 'Even'
		 case 465: 
 			 return 'Odd'
		 case 466: 
 			 return 'Even'
		 case 467: 
 			 return 'Odd'
		 case 468: 
 			 return 'Even'
		 case 469: 
 			 return 'Odd'
		 case 470: 
 			 return 'Even'
		 case 471: 
 			 return 'Odd'
		 case 472: 
 			 return 'Even'
		 case 473: 
 			 return 'Odd'
		 case 474: 
 			 return 'Even'
		 case 475: 
 			 return 'Odd'
		 case 476: 
 			 return 'Even'
		 case 477: 
 			 return 'Odd'
		 case 478: 
 			 return 'Even'
		 case 479: 
 			 return 'Odd'
		 case 480: 
 			 return 'Even'
		 case 481: 
 			 return 'Odd'
		 case 482: 
 			 return 'Even'
		 case 483: 
 			 return 'Odd'
		 case 484: 
 			 return 'Even'
		 case 485: 
 			 return 'Odd'
		 case 486: 
 			 return 'Even'
		 case 487: 
 			 return 'Odd'
		 case 488: 
 			 return 'Even'
		 case 489: 
 			 return 'Odd'
		 case 490: 
 			 return 'Even'
		 case 491: 
 			 return 'Odd'
		 case 492: 
 			 return 'Even'
		 case 493: 
 			 return 'Odd'
		 case 494: 
 			 return 'Even'
		 case 495: 
 			 return 'Odd'
		 case 496: 
 			 return 'Even'
		 case 497: 
 			 return 'Odd'
		 case 498: 
 			 return 'Even'
		 case 499: 
 			 return 'Odd'
		 case 500: 
 			 return 'Even'
		 case 501: 
 			 return 'Odd'
		 case 502: 
 			 return 'Even'
		 case 503: 
 			 return 'Odd'
		 case 504: 
 			 return 'Even'
		 case 505: 
 			 return 'Odd'
		 case 506: 
 			 return 'Even'
		 case 507: 
 			 return 'Odd'
		 case 508: 
 			 return 'Even'
		 case 509: 
 			 return 'Odd'
		 case 510: 
 			 return 'Even'
		 case 511: 
 			 return 'Odd'
		 case 512: 
 			 return 'Even'
		 case 513: 
 			 return 'Odd'
		 case 514: 
 			 return 'Even'
		 case 515: 
 			 return 'Odd'
		 case 516: 
 			 return 'Even'
		 case 517: 
 			 return 'Odd'
		 case 518: 
 			 return 'Even'
		 case 519: 
 			 return 'Odd'
		 case 520: 
 			 return 'Even'
		 case 521: 
 			 return 'Odd'
		 case 522: 
 			 return 'Even'
		 case 523: 
 			 return 'Odd'
		 case 524: 
 			 return 'Even'
		 case 525: 
 			 return 'Odd'
		 case 526: 
 			 return 'Even'
		 case 527: 
 			 return 'Odd'
		 case 528: 
 			 return 'Even'
		 case 529: 
 			 return 'Odd'
		 case 530: 
 			 return 'Even'
		 case 531: 
 			 return 'Odd'
		 case 532: 
 			 return 'Even'
		 case 533: 
 			 return 'Odd'
		 case 534: 
 			 return 'Even'
		 case 535: 
 			 return 'Odd'
		 case 536: 
 			 return 'Even'
		 case 537: 
 			 return 'Odd'
		 case 538: 
 			 return 'Even'
		 case 539: 
 			 return 'Odd'
		 case 540: 
 			 return 'Even'
		 case 541: 
 			 return 'Odd'
		 case 542: 
 			 return 'Even'
		 case 543: 
 			 return 'Odd'
		 case 544: 
 			 return 'Even'
		 case 545: 
 			 return 'Odd'
		 case 546: 
 			 return 'Even'
		 case 547: 
 			 return 'Odd'
		 case 548: 
 			 return 'Even'
		 case 549: 
 			 return 'Odd'
		 case 550: 
 			 return 'Even'
		 case 551: 
 			 return 'Odd'
		 case 552: 
 			 return 'Even'
		 case 553: 
 			 return 'Odd'
		 case 554: 
 			 return 'Even'
		 case 555: 
 			 return 'Odd'
		 case 556: 
 			 return 'Even'
		 case 557: 
 			 return 'Odd'
		 case 558: 
 			 return 'Even'
		 case 559: 
 			 return 'Odd'
		 case 560: 
 			 return 'Even'
		 case 561: 
 			 return 'Odd'
		 case 562: 
 			 return 'Even'
		 case 563: 
 			 return 'Odd'
		 case 564: 
 			 return 'Even'
		 case 565: 
 			 return 'Odd'
		 case 566: 
 			 return 'Even'
		 case 567: 
 			 return 'Odd'
		 case 568: 
 			 return 'Even'
		 case 569: 
 			 return 'Odd'
		 case 570: 
 			 return 'Even'
		 case 571: 
 			 return 'Odd'
		 case 572: 
 			 return 'Even'
		 case 573: 
 			 return 'Odd'
		 case 574: 
 			 return 'Even'
		 case 575: 
 			 return 'Odd'
		 case 576: 
 			 return 'Even'
		 case 577: 
 			 return 'Odd'
		 case 578: 
 			 return 'Even'
		 case 579: 
 			 return 'Odd'
		 case 580: 
 			 return 'Even'
		 case 581: 
 			 return 'Odd'
		 case 582: 
 			 return 'Even'
		 case 583: 
 			 return 'Odd'
		 case 584: 
 			 return 'Even'
		 case 585: 
 			 return 'Odd'
		 case 586: 
 			 return 'Even'
		 case 587: 
 			 return 'Odd'
		 case 588: 
 			 return 'Even'
		 case 589: 
 			 return 'Odd'
		 case 590: 
 			 return 'Even'
		 case 591: 
 			 return 'Odd'
		 case 592: 
 			 return 'Even'
		 case 593: 
 			 return 'Odd'
		 case 594: 
 			 return 'Even'
		 case 595: 
 			 return 'Odd'
		 case 596: 
 			 return 'Even'
		 case 597: 
 			 return 'Odd'
		 case 598: 
 			 return 'Even'
		 case 599: 
 			 return 'Odd'
		 case 600: 
 			 return 'Even'
		 case 601: 
 			 return 'Odd'
		 case 602: 
 			 return 'Even'
		 case 603: 
 			 return 'Odd'
		 case 604: 
 			 return 'Even'
		 case 605: 
 			 return 'Odd'
		 case 606: 
 			 return 'Even'
		 case 607: 
 			 return 'Odd'
		 case 608: 
 			 return 'Even'
		 case 609: 
 			 return 'Odd'
		 case 610: 
 			 return 'Even'
		 case 611: 
 			 return 'Odd'
		 case 612: 
 			 return 'Even'
		 case 613: 
 			 return 'Odd'
		 case 614: 
 			 return 'Even'
		 case 615: 
 			 return 'Odd'
		 case 616: 
 			 return 'Even'
		 case 617: 
 			 return 'Odd'
		 case 618: 
 			 return 'Even'
		 case 619: 
 			 return 'Odd'
		 case 620: 
 			 return 'Even'
		 case 621: 
 			 return 'Odd'
		 case 622: 
 			 return 'Even'
		 case 623: 
 			 return 'Odd'
		 case 624: 
 			 return 'Even'
		 case 625: 
 			 return 'Odd'
		 case 626: 
 			 return 'Even'
		 case 627: 
 			 return 'Odd'
		 case 628: 
 			 return 'Even'
		 case 629: 
 			 return 'Odd'
		 case 630: 
 			 return 'Even'
		 case 631: 
 			 return 'Odd'
		 case 632: 
 			 return 'Even'
		 case 633: 
 			 return 'Odd'
		 case 634: 
 			 return 'Even'
		 case 635: 
 			 return 'Odd'
		 case 636: 
 			 return 'Even'
		 case 637: 
 			 return 'Odd'
		 case 638: 
 			 return 'Even'
		 case 639: 
 			 return 'Odd'
		 case 640: 
 			 return 'Even'
		 case 641: 
 			 return 'Odd'
		 case 642: 
 			 return 'Even'
		 case 643: 
 			 return 'Odd'
		 case 644: 
 			 return 'Even'
		 case 645: 
 			 return 'Odd'
		 case 646: 
 			 return 'Even'
		 case 647: 
 			 return 'Odd'
		 case 648: 
 			 return 'Even'
		 case 649: 
 			 return 'Odd'
		 case 650: 
 			 return 'Even'
		 case 651: 
 			 return 'Odd'
		 case 652: 
 			 return 'Even'
		 case 653: 
 			 return 'Odd'
		 case 654: 
 			 return 'Even'
		 case 655: 
 			 return 'Odd'
		 case 656: 
 			 return 'Even'
		 case 657: 
 			 return 'Odd'
		 case 658: 
 			 return 'Even'
		 case 659: 
 			 return 'Odd'
		 case 660: 
 			 return 'Even'
		 case 661: 
 			 return 'Odd'
		 case 662: 
 			 return 'Even'
		 case 663: 
 			 return 'Odd'
		 case 664: 
 			 return 'Even'
		 case 665: 
 			 return 'Odd'
		 case 666: 
 			 return 'Even'
		 case 667: 
 			 return 'Odd'
		 case 668: 
 			 return 'Even'
		 case 669: 
 			 return 'Odd'
		 case 670: 
 			 return 'Even'
		 case 671: 
 			 return 'Odd'
		 case 672: 
 			 return 'Even'
		 case 673: 
 			 return 'Odd'
		 case 674: 
 			 return 'Even'
		 case 675: 
 			 return 'Odd'
		 case 676: 
 			 return 'Even'
		 case 677: 
 			 return 'Odd'
		 case 678: 
 			 return 'Even'
		 case 679: 
 			 return 'Odd'
		 case 680: 
 			 return 'Even'
		 case 681: 
 			 return 'Odd'
		 case 682: 
 			 return 'Even'
		 case 683: 
 			 return 'Odd'
		 case 684: 
 			 return 'Even'
		 case 685: 
 			 return 'Odd'
		 case 686: 
 			 return 'Even'
		 case 687: 
 			 return 'Odd'
		 case 688: 
 			 return 'Even'
		 case 689: 
 			 return 'Odd'
		 case 690: 
 			 return 'Even'
		 case 691: 
 			 return 'Odd'
		 case 692: 
 			 return 'Even'
		 case 693: 
 			 return 'Odd'
		 case 694: 
 			 return 'Even'
		 case 695: 
 			 return 'Odd'
		 case 696: 
 			 return 'Even'
		 case 697: 
 			 return 'Odd'
		 case 698: 
 			 return 'Even'
		 case 699: 
 			 return 'Odd'
		 case 700: 
 			 return 'Even'
		 case 701: 
 			 return 'Odd'
		 case 702: 
 			 return 'Even'
		 case 703: 
 			 return 'Odd'
		 case 704: 
 			 return 'Even'
		 case 705: 
 			 return 'Odd'
		 case 706: 
 			 return 'Even'
		 case 707: 
 			 return 'Odd'
		 case 708: 
 			 return 'Even'
		 case 709: 
 			 return 'Odd'
		 case 710: 
 			 return 'Even'
		 case 711: 
 			 return 'Odd'
		 case 712: 
 			 return 'Even'
		 case 713: 
 			 return 'Odd'
		 case 714: 
 			 return 'Even'
		 case 715: 
 			 return 'Odd'
		 case 716: 
 			 return 'Even'
		 case 717: 
 			 return 'Odd'
		 case 718: 
 			 return 'Even'
		 case 719: 
 			 return 'Odd'
		 case 720: 
 			 return 'Even'
		 case 721: 
 			 return 'Odd'
		 case 722: 
 			 return 'Even'
		 case 723: 
 			 return 'Odd'
		 case 724: 
 			 return 'Even'
		 case 725: 
 			 return 'Odd'
		 case 726: 
 			 return 'Even'
		 case 727: 
 			 return 'Odd'
		 case 728: 
 			 return 'Even'
		 case 729: 
 			 return 'Odd'
		 case 730: 
 			 return 'Even'
		 case 731: 
 			 return 'Odd'
		 case 732: 
 			 return 'Even'
		 case 733: 
 			 return 'Odd'
		 case 734: 
 			 return 'Even'
		 case 735: 
 			 return 'Odd'
		 case 736: 
 			 return 'Even'
		 case 737: 
 			 return 'Odd'
		 case 738: 
 			 return 'Even'
		 case 739: 
 			 return 'Odd'
		 case 740: 
 			 return 'Even'
		 case 741: 
 			 return 'Odd'
		 case 742: 
 			 return 'Even'
		 case 743: 
 			 return 'Odd'
		 case 744: 
 			 return 'Even'
		 case 745: 
 			 return 'Odd'
		 case 746: 
 			 return 'Even'
		 case 747: 
 			 return 'Odd'
		 case 748: 
 			 return 'Even'
		 case 749: 
 			 return 'Odd'
		 case 750: 
 			 return 'Even'
		 case 751: 
 			 return 'Odd'
		 case 752: 
 			 return 'Even'
		 case 753: 
 			 return 'Odd'
		 case 754: 
 			 return 'Even'
		 case 755: 
 			 return 'Odd'
		 case 756: 
 			 return 'Even'
		 case 757: 
 			 return 'Odd'
		 case 758: 
 			 return 'Even'
		 case 759: 
 			 return 'Odd'
		 case 760: 
 			 return 'Even'
		 case 761: 
 			 return 'Odd'
		 case 762: 
 			 return 'Even'
		 case 763: 
 			 return 'Odd'
		 case 764: 
 			 return 'Even'
		 case 765: 
 			 return 'Odd'
		 case 766: 
 			 return 'Even'
		 case 767: 
 			 return 'Odd'
		 case 768: 
 			 return 'Even'
		 case 769: 
 			 return 'Odd'
		 case 770: 
 			 return 'Even'
		 case 771: 
 			 return 'Odd'
		 case 772: 
 			 return 'Even'
		 case 773: 
 			 return 'Odd'
		 case 774: 
 			 return 'Even'
		 case 775: 
 			 return 'Odd'
		 case 776: 
 			 return 'Even'
		 case 777: 
 			 return 'Odd'
		 case 778: 
 			 return 'Even'
		 case 779: 
 			 return 'Odd'
		 case 780: 
 			 return 'Even'
		 case 781: 
 			 return 'Odd'
		 case 782: 
 			 return 'Even'
		 case 783: 
 			 return 'Odd'
		 case 784: 
 			 return 'Even'
		 case 785: 
 			 return 'Odd'
		 case 786: 
 			 return 'Even'
		 case 787: 
 			 return 'Odd'
		 case 788: 
 			 return 'Even'
		 case 789: 
 			 return 'Odd'
		 case 790: 
 			 return 'Even'
		 case 791: 
 			 return 'Odd'
		 case 792: 
 			 return 'Even'
		 case 793: 
 			 return 'Odd'
		 case 794: 
 			 return 'Even'
		 case 795: 
 			 return 'Odd'
		 case 796: 
 			 return 'Even'
		 case 797: 
 			 return 'Odd'
		 case 798: 
 			 return 'Even'
		 case 799: 
 			 return 'Odd'
		 case 800: 
 			 return 'Even'
		 case 801: 
 			 return 'Odd'
		 case 802: 
 			 return 'Even'
		 case 803: 
 			 return 'Odd'
		 case 804: 
 			 return 'Even'
		 case 805: 
 			 return 'Odd'
		 case 806: 
 			 return 'Even'
		 case 807: 
 			 return 'Odd'
		 case 808: 
 			 return 'Even'
		 case 809: 
 			 return 'Odd'
		 case 810: 
 			 return 'Even'
		 case 811: 
 			 return 'Odd'
		 case 812: 
 			 return 'Even'
		 case 813: 
 			 return 'Odd'
		 case 814: 
 			 return 'Even'
		 case 815: 
 			 return 'Odd'
		 case 816: 
 			 return 'Even'
		 case 817: 
 			 return 'Odd'
		 case 818: 
 			 return 'Even'
		 case 819: 
 			 return 'Odd'
		 case 820: 
 			 return 'Even'
		 case 821: 
 			 return 'Odd'
		 case 822: 
 			 return 'Even'
		 case 823: 
 			 return 'Odd'
		 case 824: 
 			 return 'Even'
		 case 825: 
 			 return 'Odd'
		 case 826: 
 			 return 'Even'
		 case 827: 
 			 return 'Odd'
		 case 828: 
 			 return 'Even'
		 case 829: 
 			 return 'Odd'
		 case 830: 
 			 return 'Even'
		 case 831: 
 			 return 'Odd'
		 case 832: 
 			 return 'Even'
		 case 833: 
 			 return 'Odd'
		 case 834: 
 			 return 'Even'
		 case 835: 
 			 return 'Odd'
		 case 836: 
 			 return 'Even'
		 case 837: 
 			 return 'Odd'
		 case 838: 
 			 return 'Even'
		 case 839: 
 			 return 'Odd'
		 case 840: 
 			 return 'Even'
		 case 841: 
 			 return 'Odd'
		 case 842: 
 			 return 'Even'
		 case 843: 
 			 return 'Odd'
		 case 844: 
 			 return 'Even'
		 case 845: 
 			 return 'Odd'
		 case 846: 
 			 return 'Even'
		 case 847: 
 			 return 'Odd'
		 case 848: 
 			 return 'Even'
		 case 849: 
 			 return 'Odd'
		 case 850: 
 			 return 'Even'
		 case 851: 
 			 return 'Odd'
		 case 852: 
 			 return 'Even'
		 case 853: 
 			 return 'Odd'
		 case 854: 
 			 return 'Even'
		 case 855: 
 			 return 'Odd'
		 case 856: 
 			 return 'Even'
		 case 857: 
 			 return 'Odd'
		 case 858: 
 			 return 'Even'
		 case 859: 
 			 return 'Odd'
		 case 860: 
 			 return 'Even'
		 case 861: 
 			 return 'Odd'
		 case 862: 
 			 return 'Even'
		 case 863: 
 			 return 'Odd'
		 case 864: 
 			 return 'Even'
		 case 865: 
 			 return 'Odd'
		 case 866: 
 			 return 'Even'
		 case 867: 
 			 return 'Odd'
		 case 868: 
 			 return 'Even'
		 case 869: 
 			 return 'Odd'
		 case 870: 
 			 return 'Even'
		 case 871: 
 			 return 'Odd'
		 case 872: 
 			 return 'Even'
		 case 873: 
 			 return 'Odd'
		 case 874: 
 			 return 'Even'
		 case 875: 
 			 return 'Odd'
		 case 876: 
 			 return 'Even'
		 case 877: 
 			 return 'Odd'
		 case 878: 
 			 return 'Even'
		 case 879: 
 			 return 'Odd'
		 case 880: 
 			 return 'Even'
		 case 881: 
 			 return 'Odd'
		 case 882: 
 			 return 'Even'
		 case 883: 
 			 return 'Odd'
		 case 884: 
 			 return 'Even'
		 case 885: 
 			 return 'Odd'
		 case 886: 
 			 return 'Even'
		 case 887: 
 			 return 'Odd'
		 case 888: 
 			 return 'Even'
		 case 889: 
 			 return 'Odd'
		 case 890: 
 			 return 'Even'
		 case 891: 
 			 return 'Odd'
		 case 892: 
 			 return 'Even'
		 case 893: 
 			 return 'Odd'
		 case 894: 
 			 return 'Even'
		 case 895: 
 			 return 'Odd'
		 case 896: 
 			 return 'Even'
		 case 897: 
 			 return 'Odd'
		 case 898: 
 			 return 'Even'
		 case 899: 
 			 return 'Odd'
		 case 900: 
 			 return 'Even'
		 case 901: 
 			 return 'Odd'
		 case 902: 
 			 return 'Even'
		 case 903: 
 			 return 'Odd'
		 case 904: 
 			 return 'Even'
		 case 905: 
 			 return 'Odd'
		 case 906: 
 			 return 'Even'
		 case 907: 
 			 return 'Odd'
		 case 908: 
 			 return 'Even'
		 case 909: 
 			 return 'Odd'
		 case 910: 
 			 return 'Even'
		 case 911: 
 			 return 'Odd'
		 case 912: 
 			 return 'Even'
		 case 913: 
 			 return 'Odd'
		 case 914: 
 			 return 'Even'
		 case 915: 
 			 return 'Odd'
		 case 916: 
 			 return 'Even'
		 case 917: 
 			 return 'Odd'
		 case 918: 
 			 return 'Even'
		 case 919: 
 			 return 'Odd'
		 case 920: 
 			 return 'Even'
		 case 921: 
 			 return 'Odd'
		 case 922: 
 			 return 'Even'
		 case 923: 
 			 return 'Odd'
		 case 924: 
 			 return 'Even'
		 case 925: 
 			 return 'Odd'
		 case 926: 
 			 return 'Even'
		 case 927: 
 			 return 'Odd'
		 case 928: 
 			 return 'Even'
		 case 929: 
 			 return 'Odd'
		 case 930: 
 			 return 'Even'
		 case 931: 
 			 return 'Odd'
		 case 932: 
 			 return 'Even'
		 case 933: 
 			 return 'Odd'
		 case 934: 
 			 return 'Even'
		 case 935: 
 			 return 'Odd'
		 case 936: 
 			 return 'Even'
		 case 937: 
 			 return 'Odd'
		 case 938: 
 			 return 'Even'
		 case 939: 
 			 return 'Odd'
		 case 940: 
 			 return 'Even'
		 case 941: 
 			 return 'Odd'
		 case 942: 
 			 return 'Even'
		 case 943: 
 			 return 'Odd'
		 case 944: 
 			 return 'Even'
		 case 945: 
 			 return 'Odd'
		 case 946: 
 			 return 'Even'
		 case 947: 
 			 return 'Odd'
		 case 948: 
 			 return 'Even'
		 case 949: 
 			 return 'Odd'
		 case 950: 
 			 return 'Even'
		 case 951: 
 			 return 'Odd'
		 case 952: 
 			 return 'Even'
		 case 953: 
 			 return 'Odd'
		 case 954: 
 			 return 'Even'
		 case 955: 
 			 return 'Odd'
		 case 956: 
 			 return 'Even'
		 case 957: 
 			 return 'Odd'
		 case 958: 
 			 return 'Even'
		 case 959: 
 			 return 'Odd'
		 case 960: 
 			 return 'Even'
		 case 961: 
 			 return 'Odd'
		 case 962: 
 			 return 'Even'
		 case 963: 
 			 return 'Odd'
		 case 964: 
 			 return 'Even'
		 case 965: 
 			 return 'Odd'
		 case 966: 
 			 return 'Even'
		 case 967: 
 			 return 'Odd'
		 case 968: 
 			 return 'Even'
		 case 969: 
 			 return 'Odd'
		 case 970: 
 			 return 'Even'
		 case 971: 
 			 return 'Odd'
		 case 972: 
 			 return 'Even'
		 case 973: 
 			 return 'Odd'
		 case 974: 
 			 return 'Even'
		 case 975: 
 			 return 'Odd'
		 case 976: 
 			 return 'Even'
		 case 977: 
 			 return 'Odd'
		 case 978: 
 			 return 'Even'
		 case 979: 
 			 return 'Odd'
		 case 980: 
 			 return 'Even'
		 case 981: 
 			 return 'Odd'
		 case 982: 
 			 return 'Even'
		 case 983: 
 			 return 'Odd'
		 case 984: 
 			 return 'Even'
		 case 985: 
 			 return 'Odd'
		 case 986: 
 			 return 'Even'
		 case 987: 
 			 return 'Odd'
		 case 988: 
 			 return 'Even'
		 case 989: 
 			 return 'Odd'
		 case 990: 
 			 return 'Even'
		 case 991: 
 			 return 'Odd'
		 case 992: 
 			 return 'Even'
		 case 993: 
 			 return 'Odd'
		 case 994: 
 			 return 'Even'
		 case 995: 
 			 return 'Odd'
		 case 996: 
 			 return 'Even'
		 case 997: 
 			 return 'Odd'
		 case 998: 
 			 return 'Even'
		 case 999: 
 			 return 'Odd'
	return 'Currently Not Supported' 
print(EvenOdd(x))